### PR TITLE
WIP: Parity Support

### PR DESCRIPTION
**Pull request by tagomaru**
This PR is for parity support.
It needs to change the repos orchestration, polyswarmd, relay, and contractor as well.
The rest will be changed soon.

Please NOTE this is still WIP.

To build the image for parity, please use `Dockerfile-parity` instead of `Docker`.

### CODE REVIEW

**Review by myhndl — COMMENTED** [review]
Note: Parity is being used for sidechain; Geth is being used for homechain.

If Parity was attempted to be used for homechain, this would break because it's lacking `genesis_parity_homechain.json`

**Comment by Rizato** [comment]
The parity node here is not signing blocks, and is not POA. 

Need to add

#### config.toml
```toml
# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Kovan Test Network
chain = "genesis.json"

[account]
# File at password.txt should contain passwords to unlock your accounts. One password per line.
password = ["password.txt"]

[mining]
# Account address to receive reward when block is mined.
author = "0x34e583cf9c1789c3141538eec77d9f0b8f7e89f2"
engine_signer = "0x34e583cf9c1789c3141538eec77d9f0b8f7e89f2"
reseal_on_txs = "none"
# You will be paid $0 for a basic transaction - Minimum gas price will be set accordingly.
usd_per_tx = "0"
# Parity will reject transactions above 94000000 gas.
tx_gas_limit = "94000000"
```

And modify the genesis with
```json
"engine": {
		"authorityRound": {
			"params": {
				"stepDuration": "1",
				"validators" : {
					"multi": {
						"0": { "list": ["0x34e583cf9c1789c3141538eec77d9f0b8f7e89f2"] }
					}
				}
			}
		}
  },
```


The above doesn't work as is, but is a start towards parity working in POA mode and mining blocks every second. 

I think this will make it so we can maintain the same 15 second timeout and the wait for blocks code in contractor. Not completely sure, as I can't get the parity stuff signing blocks yet.

**Comment by Rizato** [comment]
I think also, in general it would be better to move the cli options into the config file as well. 
https://wiki.parity.io/Configuring-Parity-Ethereum

**Comment by Rizato** [comment]
I got it running in POA mode and signing.

**Comment by Rizato** [comment]
I think we are going with the polyswarm/parity and polyswarm/geth repos to replace this.

**Pull request closed without merging**
